#!/usr/local/bin/python3
import os
from django.conf import settings

# Función para el vaciado de la carpeta
def borrar_archivos_pdf():
    carpeta = settings.MEDIA_ROOT
    for archivo in os.listdir(carpeta):
        if archivo.endswith('.pdf'):
            os.remove(os.path.join(carpeta, archivo))
            print(f'Archivo borrado: {archivo}')

if __name__ == "__main__":
    borrar_archivos_pdf()
