# Generated by Django 5.0.4 on 2024-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0017_acervo_model_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='fechaedicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualiación'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
