# Generated by Django 5.0.4 on 2024-12-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_alter_acervo_model_fechaedicion_and_more'),
        ('almacen', '0022_remove_acervo_model_clave'),
    ]

    operations = [
    ]
